export const products = [
    {
        id: 1,
        name: "Kungaboqar yog'i Oila tanlovi, tozalangan va xidsizlantirilgan, 60 kg",
        image: "/src/assets/oil.png",
        badge: "Eksklyuziv",
        monthly: "1 560",
        oldPrice: "15 000",
        price: "13 000",
        rating: 4.9,
        reviews: 4092,
    },
    {
        id: 2,
        name: "Smartfon Xiaomi Redmi Note 13, 6/128 GB, 8/128 GB, 8/256GB",
        image: "/src/assets/oil.png",
        badge: "Aksiya",
        monthly: "29 880",
        oldPrice: "3 010 000",
        price: "2 499 000",
        rating: 5.0,
        reviews: 18,
    },
    {
        id: 3,
        name: "Kir yuvish kukuni Oila tanlovi 'Ayoz tazelig', avtomat, 3 kg",
        image: "/src/assets/oil.png",
        badge: "Eksklyuziv",
        monthly: "4 920",
        oldPrice: "57 000",
        price: "41 000",
        rating: 4.5,
        reviews: 173,
    },
    {
        id: 4,
        name: "Yangi tug'ilgan chaqaloqlar uchun tana to'plami 100% paxta, 3 dona",
        image: "/src/assets/oil.png",
        badge: "Aksiya",
        monthly: "11 880",
        oldPrice: "160 000",
        price: "99 000",
        rating: 3.0,
        reviews: 11,
    },
    {
        id: 5,
        name: "Sdobnoe pechenye Zarqand Brownie cookies, 490 g",
        image: "/src/assets/oil.png",
        badge: "Aksiya",
        monthly: null,
        oldPrice: null,
        price: "36 000",
        rating: null,
        reviews: null,
    },
    {
        id: 6,
        name: "Televizor Samsung Crystal UHD 4K 43'', 50'', 55'', 65'' CU7100 Smart TV",
        image: "/src/assets/oil.png",
        badge: "Aksiya",
        monthly: "587 880",
        oldPrice: "5 830 000",
        price: "4 899 000",
        rating: 4.9,
        reviews: 6,
    },
    {
        id: 7,
        name: "Avtomobil va uy uchun portativ, simsiz, kuchli JB-107 changyutgich",
        image: "/src/assets/oil.png",
        badge: "Aksiya",
        monthly: "23 880",
        oldPrice: "520 000",
        price: "199 000",
        rating: 4.7,
        reviews: 152,
    },
    {
        id: 8,
        name: "Sumka shopper ayollar uchun, yelkama, charmdan, eko zamsh",
        image: "/src/assets/oil.png",
        badge: "Aksiya",
        monthly: "11 880",
        oldPrice: "405 000",
        price: "99 000",
        rating: 5.0,
        reviews: 4,
    },
    {
        id: 9,
        name: "Smartfon Xiaomi Redmi Note 13 Pro, 8/256 GB, 12/512 GB, 6.67'', 1",
        image: "/src/assets/oil.png",
        badge: "Aksiya",
        monthly: "446 880",
        oldPrice: "5 000 000",
        price: "3 739 000",
        rating: 5.0,
        reviews: 18,
    },
    {
        id: 10,
        name: "Yostiqlar to'plami, bambukdan, gipoallergenli, ekologik toza, 70*",
        image: "/src/assets/oil.png",
        badge: "Aksiya",
        monthly: "10 680",
        oldPrice: "197 000",
        price: "89 000",
        rating: 4.5,
        reviews: 165,
    },
    {
        id: 11,
        name: "Erkaklar uchun sport kostyumi, paxta, qulay va nafas oluvchi",
        image: "/src/assets/oil.png",
        badge: "Aksiya",
        monthly: "8 400",
        oldPrice: "120 000",
        price: "70 000",
        rating: 4.8,
        reviews: 34,
    },
    {
        id: 12,
        name: "Blender stasionar, 1500W, 2L, 8 tezlik, buzilmas shisha",
        image: "/src/assets/oil.png",
        badge: "Aksiya",
        monthly: "15 600",
        oldPrice: "250 000",
        price: "130 000",
        rating: 4.6,
        reviews: 88,
    },
    {
        id: 13,
        name: "Bolalar uchun velosiped, 16 dyuym, yengil, metall rama",
        image: "/src/assets/oil.png",
        badge: "Eksklyuziv",
        monthly: "19 200",
        oldPrice: "380 000",
        price: "160 000",
        rating: 4.7,
        reviews: 52,
    },
    {
        id: 14,
        name: "Kofe mashinasi avtomatik, 1450W, 15 bar bosim, bug' funksiyasi",
        image: "/src/assets/oil.png",
        badge: "Aksiya",
        monthly: "45 600",
        oldPrice: "890 000",
        price: "380 000",
        rating: 4.9,
        reviews: 27,
    },
    {
        id: 15,
        name: "Zarbali burg'u, 800W, 13mm patron, 2 rejim, quticha bilan",
        image: "/src/assets/oil.png",
        badge: "Aksiya",
        monthly: "12 000",
        oldPrice: "180 000",
        price: "99 000",
        rating: 4.5,
        reviews: 61,
    },
    {
        id: 16,
        name: "Ayollar uchun yozgi ko'ylak, ip mato, rangli, S-XXL",
        image: "/src/assets/oil.png",
        badge: "Eksklyuziv",
        monthly: "6 000",
        oldPrice: "95 000",
        price: "49 000",
        rating: 4.8,
        reviews: 113,
    },
    {
        id: 17,
        name: "Televizor LG OLED 55'', 4K Smart TV, webOS, ThinQ AI",
        image: "/src/assets/oil.png",
        badge: "Aksiya",
        monthly: "720 000",
        oldPrice: "8 500 000",
        price: "5 990 000",
        rating: 5.0,
        reviews: 9,
    },
    {
        id: 18,
        name: "Oyoq kiyim erkaklar uchun, charm, qulay, klassik uslub",
        image: "/src/assets/oil.png",
        badge: "Aksiya",
        monthly: "9 600",
        oldPrice: "210 000",
        price: "79 000",
        rating: 4.4,
        reviews: 76,
    },
    {
        id: 19,
        name: "Muzlatgich Samsung, No Frost, 330L, 2 kamerali, A+ energiya",
        image: "/src/assets/oil.png",
        badge: "Aksiya",
        monthly: "180 000",
        oldPrice: "3 200 000",
        price: "2 650 000",
        rating: 4.9,
        reviews: 43,
    },
    {
        id: 20,
        name: "Bolalar o'yinchoq konstruktor, 500 detal, rangli, rivojlantiruvchi",
        image: "/src/assets/oil.png",
        badge: "Eksklyuziv",
        monthly: "7 200",
        oldPrice: "115 000",
        price: "59 000",
        rating: 4.7,
        reviews: 198,
    },
    {
        id: 21,
        name: "Kungaboqar yog'i Oila tanlovi, tozalangan va xidsizlantirilgan, 60 kg",
        image: "/src/assets/oil.png",
        badge: "Eksklyuziv",
        monthly: "1 560",
        oldPrice: "15 000",
        price: "13 000",
        rating: 4.9,
        reviews: 4092,
    },
    {
        id: 22,
        name: "Smartfon Xiaomi Redmi Note 13, 6/128 GB, 8/128 GB, 8/256GB",
        image: "/src/assets/oil.png",
        badge: "Aksiya",
        monthly: "29 880",
        oldPrice: "3 010 000",
        price: "2 499 000",
        rating: 5.0,
        reviews: 18,
    },
    {
        id: 23,
        name: "Kir yuvish kukuni Oila tanlovi 'Ayoz tazelig', avtomat, 3 kg",
        image: "/src/assets/oil.png",
        badge: "Eksklyuziv",
        monthly: "4 920",
        oldPrice: "57 000",
        price: "41 000",
        rating: 4.5,
        reviews: 173,
    },
    {
        id: 24,
        name: "Yangi tug'ilgan chaqaloqlar uchun tana to'plami 100% paxta, 3 dona",
        image: "/src/assets/oil.png",
        badge: "Aksiya",
        monthly: "11 880",
        oldPrice: "160 000",
        price: "99 000",
        rating: 3.0,
        reviews: 11,
    },
    {
        id: 25,
        name: "Sdobnoe pechenye Zarqand Brownie cookies, 490 g",
        image: "/src/assets/oil.png",
        badge: "Aksiya",
        monthly: null,
        oldPrice: null,
        price: "36 000",
        rating: null,
        reviews: null,
    },
]